# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trustabl < Formula
  desc "Find and fix agent reliability issues"
  homepage "https://github.com/trustabl/agent-reliability-analyzer"
  version "0.1.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trustabl/agent-reliability-analyzer/releases/download/v0.1.12/trustabl_0.1.12_darwin_amd64.tar.gz"
      sha256 "eac9bd3296a517a56e67ce07ff843677aae601b75eb641318cdee1161e9dd3a7"

      define_method(:install) do
        bin.install "trustabl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trustabl/agent-reliability-analyzer/releases/download/v0.1.12/trustabl_0.1.12_darwin_arm64.tar.gz"
      sha256 "947f37b6c32ce9f5800337e58f415517f0bb14c4528c47c70e13d04a68590b15"

      define_method(:install) do
        bin.install "trustabl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trustabl/agent-reliability-analyzer/releases/download/v0.1.12/trustabl_0.1.12_linux_amd64.tar.gz"
      sha256 "8e269726b85d079fea520eecc18951dcf73e0b8f34e8488d541b4a4588d48205"
      define_method(:install) do
        bin.install "trustabl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trustabl/agent-reliability-analyzer/releases/download/v0.1.12/trustabl_0.1.12_linux_arm64.tar.gz"
      sha256 "4295b82a53634adef66ac998c0cd53efae0fafdf4331e7f074df2093ff472944"
      define_method(:install) do
        bin.install "trustabl"
      end
    end
  end

  test do
    system "#{bin}/trustabl version"
  end
end
