# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trustabl < Formula
  desc "Find and fix agent reliability issues"
  homepage "https://github.com/trustabl/trustabl"
  version "0.1.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trustabl/trustabl/releases/download/v0.1.8/trustabl_0.1.8_darwin_amd64.tar.gz"
      sha256 "9e1251bea09ae660362f842dfe97212e34efd7efd7e530a5809010ae490ff867"

      define_method(:install) do
        bin.install "trustabl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trustabl/trustabl/releases/download/v0.1.8/trustabl_0.1.8_darwin_arm64.tar.gz"
      sha256 "63ad06065721720839022da6acb9d770799351b52093492be811179cc231c18a"

      define_method(:install) do
        bin.install "trustabl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trustabl/trustabl/releases/download/v0.1.8/trustabl_0.1.8_linux_amd64.tar.gz"
      sha256 "85116d1fc6b5d9830471f9223687e0a4e3cd72153d1f66b1752a5740c7cf1c19"
      define_method(:install) do
        bin.install "trustabl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trustabl/trustabl/releases/download/v0.1.8/trustabl_0.1.8_linux_arm64.tar.gz"
      sha256 "bc9d03d2cb089999a5e5bdcc896c54d17b1a550f5f6a2dbafa4c80d77f78406a"
      define_method(:install) do
        bin.install "trustabl"
      end
    end
  end

  test do
    system "#{bin}/trustabl version"
  end
end
