# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trustabl < Formula
  desc "Static analyzer for agent reliability"
  homepage "https://github.com/trustabl/trustabl"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trustabl/trustabl/releases/download/v0.1.0/trustabl_0.1.0_darwin_amd64.tar.gz"
      sha256 "eb2be878a7335fd126ab5695d9b2caf2fbd2831e3632b33a222da77ccfc879fb"

      define_method(:install) do
        bin.install "trustabl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trustabl/trustabl/releases/download/v0.1.0/trustabl_0.1.0_darwin_arm64.tar.gz"
      sha256 "72068e7db58a1991672472205195fe921569928bb82a46945fd9e7f316d29bf2"

      define_method(:install) do
        bin.install "trustabl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trustabl/trustabl/releases/download/v0.1.0/trustabl_0.1.0_linux_amd64.tar.gz"
      sha256 "526e786e73de9f745e518aa472bcb0b909e4adbbbbb5e52ff6426614b0843031"
      define_method(:install) do
        bin.install "trustabl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trustabl/trustabl/releases/download/v0.1.0/trustabl_0.1.0_linux_arm64.tar.gz"
      sha256 "102afcd982fc9a1606e47e34e8e904c01abfd6e6337521f5a1f084ff94a8538c"
      define_method(:install) do
        bin.install "trustabl"
      end
    end
  end

  test do
    system "#{bin}/trustabl version"
  end
end
